// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// agentChatMessagesDao is the data access object for the table john_ai_agentbox_agent_chat_messages.
// You can define custom methods on it to extend its functionality as needed.
type agentChatMessagesDao struct {
	*internal.AgentChatMessagesDao
}

var (
	// AgentChatMessages is a globally accessible object for table john_ai_agentbox_agent_chat_messages operations.
	AgentChatMessages = agentChatMessagesDao{internal.NewAgentChatMessagesDao()}
)

// Add your custom methods and functionality below.
