// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// agentChatInteractionsDao is the data access object for the table john_ai_agentbox_agent_chat_interactions.
// You can define custom methods on it to extend its functionality as needed.
type agentChatInteractionsDao struct {
	*internal.AgentChatInteractionsDao
}

var (
	// AgentChatInteractions is a globally accessible object for table john_ai_agentbox_agent_chat_interactions operations.
	AgentChatInteractions = agentChatInteractionsDao{internal.NewAgentChatInteractionsDao()}
)

// Add your custom methods and functionality below.
