// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// agentTerminalSessionsDao is the data access object for the table john_ai_agentbox_agent_terminal_sessions.
// You can define custom methods on it to extend its functionality as needed.
type agentTerminalSessionsDao struct {
	*internal.AgentTerminalSessionsDao
}

var (
	// AgentTerminalSessions is a globally accessible object for table john_ai_agentbox_agent_terminal_sessions operations.
	AgentTerminalSessions = agentTerminalSessionsDao{internal.NewAgentTerminalSessionsDao()}
)

// Add your custom methods and functionality below.
