// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// agentRuntimesDao is the data access object for the table john_ai_agentbox_agent_runtimes.
// You can define custom methods on it to extend its functionality as needed.
type agentRuntimesDao struct {
	*internal.AgentRuntimesDao
}

var (
	// AgentRuntimes is a globally accessible object for table john_ai_agentbox_agent_runtimes operations.
	AgentRuntimes = agentRuntimesDao{internal.NewAgentRuntimesDao()}
)

// Add your custom methods and functionality below.
