// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// agentChatSessionsDao is the data access object for the table john_ai_agentbox_agent_chat_sessions.
// You can define custom methods on it to extend its functionality as needed.
type agentChatSessionsDao struct {
	*internal.AgentChatSessionsDao
}

var (
	// AgentChatSessions is a globally accessible object for table john_ai_agentbox_agent_chat_sessions operations.
	AgentChatSessions = agentChatSessionsDao{internal.NewAgentChatSessionsDao()}
)

// Add your custom methods and functionality below.
