// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// aiCapabilityTiersDao is the data access object for the table john_ai_agentbox_ai_capability_tiers.
// You can define custom methods on it to extend its functionality as needed.
type aiCapabilityTiersDao struct {
	*internal.AiCapabilityTiersDao
}

var (
	// AiCapabilityTiers is a globally accessible object for table john_ai_agentbox_ai_capability_tiers operations.
	AiCapabilityTiers = aiCapabilityTiersDao{internal.NewAiCapabilityTiersDao()}
)

// Add your custom methods and functionality below.
