// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// aiCapabilityBindingsDao is the data access object for the table john_ai_agentbox_ai_capability_bindings.
// You can define custom methods on it to extend its functionality as needed.
type aiCapabilityBindingsDao struct {
	*internal.AiCapabilityBindingsDao
}

var (
	// AiCapabilityBindings is a globally accessible object for table john_ai_agentbox_ai_capability_bindings operations.
	AiCapabilityBindings = aiCapabilityBindingsDao{internal.NewAiCapabilityBindingsDao()}
)

// Add your custom methods and functionality below.
