// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// aiInvocationLogsDao is the data access object for the table john_ai_agentbox_ai_invocation_logs.
// You can define custom methods on it to extend its functionality as needed.
type aiInvocationLogsDao struct {
	*internal.AiInvocationLogsDao
}

var (
	// AiInvocationLogs is a globally accessible object for table john_ai_agentbox_ai_invocation_logs operations.
	AiInvocationLogs = aiInvocationLogsDao{internal.NewAiInvocationLogsDao()}
)

// Add your custom methods and functionality below.
