// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// aiProvidersDao is the data access object for the table john_ai_agentbox_ai_providers.
// You can define custom methods on it to extend its functionality as needed.
type aiProvidersDao struct {
	*internal.AiProvidersDao
}

var (
	// AiProviders is a globally accessible object for table john_ai_agentbox_ai_providers operations.
	AiProviders = aiProvidersDao{internal.NewAiProvidersDao()}
)

// Add your custom methods and functionality below.
