// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// codingAgentsDao is the data access object for the table john_ai_agentbox_coding_agents.
// You can define custom methods on it to extend its functionality as needed.
type codingAgentsDao struct {
	*internal.CodingAgentsDao
}

var (
	// CodingAgents is a globally accessible object for table john_ai_agentbox_coding_agents operations.
	CodingAgents = codingAgentsDao{internal.NewCodingAgentsDao()}
)

// Add your custom methods and functionality below.
