// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// codingImagesDao is the data access object for the table john_ai_agentbox_coding_images.
// You can define custom methods on it to extend its functionality as needed.
type codingImagesDao struct {
	*internal.CodingImagesDao
}

var (
	// CodingImages is a globally accessible object for table john_ai_agentbox_coding_images operations.
	CodingImages = codingImagesDao{internal.NewCodingImagesDao()}
)

// Add your custom methods and functionality below.
