// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// providerModelsDao is the data access object for the table john_ai_agentbox_provider_models.
// You can define custom methods on it to extend its functionality as needed.
type providerModelsDao struct {
	*internal.ProviderModelsDao
}

var (
	// ProviderModels is a globally accessible object for table john_ai_agentbox_provider_models operations.
	ProviderModels = providerModelsDao{internal.NewProviderModelsDao()}
)

// Add your custom methods and functionality below.
