// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// systemPromptOverridesDao is the data access object for the table john_ai_agentbox_system_prompt_overrides.
// You can define custom methods on it to extend its functionality as needed.
type systemPromptOverridesDao struct {
	*internal.SystemPromptOverridesDao
}

var (
	// SystemPromptOverrides is a globally accessible object for table john_ai_agentbox_system_prompt_overrides operations.
	SystemPromptOverrides = systemPromptOverridesDao{internal.NewSystemPromptOverridesDao()}
)

// Add your custom methods and functionality below.
