// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"john-ai-agentbox/backend/internal/dao/internal"
)

// userSessionsDao is the data access object for the table john_ai_agentbox_user_sessions.
// You can define custom methods on it to extend its functionality as needed.
type userSessionsDao struct {
	*internal.UserSessionsDao
}

var (
	// UserSessions is a globally accessible object for table john_ai_agentbox_user_sessions operations.
	UserSessions = userSessionsDao{internal.NewUserSessionsDao()}
)

// Add your custom methods and functionality below.
